### ISSUE TITLE
Take GitHub user name instead of url

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/winwin-team#1]
Right now, the `src/data/index.js` expects the whole GitHub url.
Change the code so that the Person component just expects the user name.

- [x] Remove `https://github.com/` from the gitHub values in `src/data/index.js`
- [x] Adjust `src/components/Person/index.jsx` to compensate for the new data
- [x] Add info to README.md

**Comment by eselkin** [comment]
completed by @alfredoarriolajr
