### ISSUE TITLE
Take LinkedIn user name instead of url

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/winwin-team#2]
Right now, the `src/data/index.js` expects the whole LinkedIn profile url.
Change the code so that the Person component just expects the user name.

- [ ] Remove `https://linkedin.com/in/` from the linkedIn values in `src/data/index.js`
- [ ] Adjust `src/components/Person/index.jsx` to compensate for the new data
- [ ] Edit info in README.md (user name instead of url)

**Comment by eselkin** [comment]
the prefix for linkedin is not the same in all countries.

**Comment by manonthemat** [comment]
> the prefix for linkedin is not the same in all countries.

Good catch! Closing this and change to wontfix.
