### ISSUE TITLE
Bios Collection and Improvement

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/winwin-team#3]
The purpose in having a team page is to showcase to Project Catalyst’s Community Advisor that is extremely likely that we are going to deliver what we promised we would. While not wanting to selling ourselves short, I propose we collect the vast and deep experience of our team members and highlight credentials and qualities in an easily digestible (and preferably verifiable) form to get that 5-star rating.

This can be in the form of bullet points (as of HEAD at 6767b54a2281eab0cb15ee65d3e70546a68920c5) or paragraph form with extensive use of markdown to highlight keywords. Once that decision is made, we should uniformly apply this to all team members.

Tasks as I see it:

- [x] collect bios from all team members
- [x] make it concise and highly relevant
- [x] if it's not compelling enough, dig deeper and find the value of the team member if the team member cannot surface it themself
- [x] include LinkedIn and/or GitHub profiles

**Comment by NanaSafo01** [comment]
• Active Community Advisor on Project Catalyst.
• Ambassador for GCTU WADA.
• Greater Accra Regional Head for Blockchain Education Network.
• Independent Representative for QNET.
• 5 years experience in Presentations. (Business,  Products, Services and Projects).
• BSc. Information Technology at GCTU.

**Comment by manonthemat** [comment]
@agalloch88 @eselkin please update the status of this ticket
